name: unittests
on: 
  pull_request:
    branches: [main]
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  unittests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: run unittests
        run: |
          PYTHONPATH=src python3 -m pytest -s